language: go
go_import_path: github.com/teachain/goreleaser
jobs:
  include:
  - stage: build
    os: linux
    dist: xenial
    go: 1.12.x
    env:
    - GO111MODULE=on
    - DEPLOY=true
    script:
    - go test -v ./...
deploy:
- provider: script
  script: docker run -e GITHUB_TOKEN=$GITHUB_TOKEN --rm --privileged -v $TRAVIS_BUILD_DIR:/go/src/github.com/teachain/goreleaser -v /var/run/docker.sock:/var/run/docker.sock -w /go/src/github.com/teachain/goreleaser mailchain/goreleaser-xcgo --rm-dist
  skip_cleanup: true
  on:
    # Skipping a deployment with the script provider because this is not a tagged commit
    #tags: true
    repo: teachain/goreleaser
    branch: master
    condition: $DEPLOY = true